---
-  hosts: R4
   gather_facts: false
   connection: ansible.netcommon.network_cli
   tasks:
     - name: Gather only the config and default facts
       cisco.ios.ios_facts:
         gather_subset:
         - config
       register: result
     - name: Display result to terminal
       debug:
         var: result.stdout_lines
     - name: run show version on router
       ios_command:
         command: show version | incl Version
       register: output
     - name: print oputput
       debug:
         var: output.stdout_lines

