---
-  hosts: R4
   gather_facts: false
   connection: ansible.netcommon.network_cli
   tasks:
     - name: Gather only the config and default facts
       cisco.ios.ios_facts:
         gather_subset:
         - config
~
~
